name: Deploy to Test Link

on:
  push:
    branches:
      - develop
    workflow_dispatch:

jobs:
  deploy_test_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository (팀 레포)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push changes to test repository
        env:
          TEST_DEPLOY_REPO: ${{ secrets.TEST_DEPLOY_REPO }}
        run: |
          git config user.name "Kjiw0n"
          git config user.email "rwd0904@naver.com"
          git remote add test "$TEST_DEPLOY_REPO"
          git push --force test develop
